### PR TITLE
franklin 4 architecture

### PR DESCRIPTION
**Pull request by trieloff**
- chore: update architecture
- docs(architecture): tweak visual style of architecture diagram
- docs(architecture): add diagrams for franklin 4 architecture, with AWS and Cloudflare Variants

### CODE REVIEW

**Review by tripodsan — APPROVED** [review]

**Comment by stefan-guggisberg** [comment]
Currently the Cloudflare stack is using Azure Service Bus for the forms queue. In the future we'll probably want to use [Cloudflare Queues ](https://developers.cloudflare.com/queues/).

**Review by stefan-guggisberg — COMMENTED** [review]
Currently the Cloudflare stack is using Azure Service Bus for the forms queue. In the future we'll probably want to use [Cloudflare Queues ](https://developers.cloudflare.com/queues/).

**Comment by trieloff** [comment]
@stefan-guggisberg I've updated the Cloudflare diagram to separate the forms queue (Azure) from the Index queue (AWS). @tripodsan this change also separated the two queues within AWS SQS, I hope that's correct.

**Comment by tripodsan** [comment]
> two queues within AWS SQS, I hope that's correct.

yes. although, currently there is an index queue for each project. but we're about to simplify that and have a unified queue.
forms-service has only one.

but then, there is also a queue for the cron jobs.... @dominique-pfister

**Pull request merged**
